"""Task risk assessment for Phase 8 human-review gates."""

from __future__ import annotations

import json
import re
import sqlite3
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Sequence

from .policy import detect_risk_signals

_SECRET_PATTERNS = (
    re.compile(r"(?i)(api[_-]?key|secret|password|token)\s*=\s*\S+"),
    re.compile(r"(?i)-----BEGIN (?:RSA |EC )?PRIVATE KEY-----"),
)

_GENERATED_MARKERS = (
    ".generated.",
    "/generated/",
    "autogenerated",
    "auto-generated",
)


@dataclass(frozen=True)
class RiskAssessment:
    project_id: str
    task_id: str
    risk_level: str
    reasons: tuple[str, ...]
    requires_human_review: bool
    created_at: str


def _iso_now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat()


def _normalize_path(path: str) -> str:
    return path.replace("\\", "/")


def _secret_signals(diff_text: str) -> list[str]:
    reasons: list[str] = []
    for pattern in _SECRET_PATTERNS:
        if pattern.search(diff_text):
            reasons.append("secret-looking credential diff detected")
            break
    return reasons


def _generated_file_signals(changed_files: Sequence[str]) -> list[str]:
    reasons: list[str] = []
    for path in changed_files:
        normalized = _normalize_path(path).lower()
        if any(marker in normalized for marker in _GENERATED_MARKERS):
            reasons.append(f"generated file touched: {path}")
    return reasons


def _large_diff_signal(diff_text: str, *, threshold: int = 500) -> list[str]:
    line_count = len([line for line in diff_text.splitlines() if line.startswith(("+", "-"))])
    if line_count >= threshold:
        return [f"large diff ({line_count} changed lines)"]
    return []


def _risk_level(reasons: Sequence[str]) -> str:
    if not reasons:
        return "low"
    high_markers = ("migration", "secret", "credential", "protected path", "dependency")
    if any(any(marker in reason.lower() for marker in high_markers) for reason in reasons):
        return "high"
    return "medium"


def assess_task_risk(
    conn: sqlite3.Connection,
    *,
    project_id: str,
    task_id: str,
    changed_files: Sequence[str] | None = None,
    diff_text: str = "",
    capabilities: Sequence[str] | None = None,
    max_files_touched: int = 20,
    commit: bool = True,
) -> RiskAssessment:
    """Classify task risk and persist the latest assessment."""
    files = list(changed_files or [])
    reasons: list[str] = []

    reasons.extend(
        detect_risk_signals(
            files,
            max_files_touched=max_files_touched,
            spec_review_passed=True,
            quality_review_passed=True,
        )
    )
    reasons.extend(_secret_signals(diff_text))
    reasons.extend(_generated_file_signals(files))
    reasons.extend(_large_diff_signal(diff_text))

    caps = [part for part in (capabilities or []) if part]
    if "code" in caps and not files:
        reasons.append("code task produced no changed files")

    deduped = list(dict.fromkeys(reasons))
    level = _risk_level(deduped)
    requires_human = bool(deduped) or level != "low"
    created_at = _iso_now()

    conn.execute(
        """
        insert into task_risk_assessments(
            project_id, task_id, risk_level, reasons_json,
            requires_human_review, created_at
        ) values (?, ?, ?, ?, ?, ?)
        """,
        (
            project_id,
            task_id,
            level,
            json.dumps(deduped),
            1 if requires_human else 0,
            created_at,
        ),
    )
    if commit:
        conn.commit()

    return RiskAssessment(
        project_id=project_id,
        task_id=task_id,
        risk_level=level,
        reasons=tuple(deduped),
        requires_human_review=requires_human,
        created_at=created_at,
    )


def get_latest_risk_assessment(
    conn: sqlite3.Connection,
    *,
    project_id: str,
    task_id: str,
) -> RiskAssessment | None:
    """Return the most recent persisted risk assessment for a task."""
    row = conn.execute(
        """
        select * from task_risk_assessments
        where project_id = ? and task_id = ?
        order by created_at desc, id desc
        limit 1
        """,
        (project_id, task_id),
    ).fetchone()
    if row is None:
        return None
    reasons = json.loads(row["reasons_json"])
    return RiskAssessment(
        project_id=str(row["project_id"]),
        task_id=str(row["task_id"]),
        risk_level=str(row["risk_level"]),
        reasons=tuple(str(item) for item in reasons),
        requires_human_review=bool(row["requires_human_review"]),
        created_at=str(row["created_at"]),
    )